version: '3.1'

services:
  echo:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env